### ISSUE TITLE
Missing servers.example.js file

### ISSUE THREAD

**Issue by grishko-ga** [DistroByte/AwF-Bot#107]
**_Where are servers.example.js file? Missing file, while installing._**

**Comment by oof2win2** [comment]
Sorry. It was on my master branch, it is here now though. Please see [this](https://github.com/oof2win2/AwF-Bot/blob/master/servers.example.js) for now, with the updated installation guide [here](https://github.com/oof2win2/AwF-Bot/blob/master/INSTALLATION.md) too.
