### ISSUE TITLE
When a player is banned, remove them from the database

### ISSUE THREAD

**Issue by oof2win2** [DistroByte/AwF-Bot#114]
When a player is banned and they are linked, remove their linked data.

**Comment by TechifyAu** [comment]
So You want to remove all the players data when they are banned, and also remove them from the database. If Im not mistaken

**Comment by TechifyAu** [comment]
And Could You Assign This To me?

**Comment by TechifyAu** [comment]
Also Just wondering, what database are you using to log the user?

**Comment by oof2win2** [comment]
> So You want to remove all the players data when they are banned, and also remove them from the database. If Im not mistaken

Only remove them from the database.

**Comment by TechifyAu** [comment]
> > So You want to remove all the players data when they are banned, and also remove them from the database. If Im not mistaken
> 
> Only remove them from the database.

Oh Ok, Btw what database are you using bc i saw you using mongodb and sqlite in your code

**Comment by oof2win2** [comment]
SQLite is only adding bans. MongoDB is other data, which is the players here. See [this](https://github.com/DistroByte/AwF-Bot/blob/master/base/User.js)

**Comment by TechifyAu** [comment]
Thank You. I will Start Working on It ASAP
