### ISSUE TITLE
Discord & Node version incompatibility

### ISSUE THREAD

**Issue by Y0dle** [DistroByte/AwF-Bot#160]
Hi, I'm having trouble getting the bot to run.  When I try using Node v14 I get an error that Discord v13 is not supported (the package.json in the repo has this version despite the readme stating v12 should be being used).  When I try to install v12 directly, I get a bunch of compile errors.  Just wondering if I've done something wrong or the installation instructions need to be updated.  Thanks.

**Comment by oof2win2** [comment]
The bot uses nodejs v16, as discordjs requires at least that now.

**Comment by Y0dle** [comment]
Ah thanks, I had gotten it working awhile ago but recently tried again and couldn't remember what I had done, that sounds familiar.
