### ISSUE TITLE
RCON connections seemingly not working sometimes

### ISSUE THREAD

**Issue by oof2win2** [DistroByte/AwF-Bot#53]
RCON connections for Factorio servers aren't working sometimes. I couldn't find any logical reasoning behind it, so here are the errors. Images show the output of `?po` before I joined, second image is after I joined.
```
0|JammyBot  | Connection Error --- Details --- 
0|JammyBot  | NAME: Error 
0|JammyBot  | DESC: undefined 
0|JammyBot  | Stack: Error: Timeout for packet id 1
0|JammyBot  |     at Timeout._onTimeout (/opt/factorio/AwF-Bot-Production/node_modules/rcon-client/lib/rcon.js:117:28)
0|JammyBot  |     at listOnTimeout (internal/timers.js:549:17)
0|JammyBot  |     at processTimers (internal/timers.js:492:7)
```

<img width="500" alt="Screenshot 2021-01-01 at 21 17 03" src="https://user-images.githubusercontent.com/23482862/103453013-e80f6480-4cd5-11eb-80cd-77df3f74355d.png">
<img width="503" alt="Screenshot 2021-01-01 at 21 17 12" src="https://user-images.githubusercontent.com/23482862/103453012-e776ce00-4cd5-11eb-9da4-1b80f6b873ab.png">

**Comment by oof2win2** [comment]
Bug hasn't occured in a longer while, therefore I am marking this as `more-info-needed`

**Comment by Maxcr1** [comment]
It's an issue with the rcon-client module.  I'm having the same issue on a completely unrelated project.

**Comment by oof2win2** [comment]
Hi, sorry for responding with this delay. As you can see above, I sent an issue to the [rcon-client repo](https://github.com/janispritzkau/rcon-client), but I will keep this issue closed, as with your insight, I believe it is not related to this project, it, however, is related to the rcon client itself. Please, correct me if I'm wrong.

**Comment by Maxcr1** [comment]
If you're only needing to send (not receive), I've discovered that you can just catch this error.  In my case, the data still gets sent, you just don't get a reply.
