### ISSUE TITLE
Bot being rate limited or something?

### ISSUE THREAD

**Issue by oof2win2** [DistroByte/AwF-Bot#79]
Can't figure out if this is a rate limit or what.
If you use the `/cheat` command in-game, it researches all tech. The bot tries to log all of that. It doesn't work well, as it takes the bot a while and it doesn't respond to any other commands.

**Comment by DistroByte** [comment]
More than likely being rate limited. It can only send 5 messages every 5 seconds I think. Same as a regular user

**Comment by oof2win2** [comment]
Plan is to use a "cache" for each server, the message sender would grab all messages until the length doesn't exceed 5000 chars (discord limit) and send them in bulk. Would work similarly as the RedMew FactorioWebInterface, except JS

**Comment by DistroByte** [comment]
So send 10, 2000 character messages instead of 200000 10 char messages. Good idea. I think the limit is 2000 characters too

**Comment by oof2win2** [comment]
Yep, it's 2k. Thanks
